### ISSUE TITLE
concurrent_unordered_map has a memory leak?

### ISSUE THREAD

**Issue by xinqiangren** [ssteinberg/ste#1]
in function:  concurrent_unordered_map::insert_update_into_virtual_bucket, new_next not delete if compare_exchange_strong fail

			if (virtual_bucket.next.compare_exchange_strong(next_ptr, new_next, std::memory_order_acq_rel, std::memory_order_acquire))
				next_ptr = new_next;

			assert(next_ptr);
		}

**Comment by ssteinberg** [comment]
Indeed. Thanks.
